global using AutoMapper;
global using GardenLog.SharedInfrastructure;
global using GardenLog.SharedInfrastructure.Extensions;
global using GrowConditions.Api.CommandHandlers;
global using GrowConditions.Api.Model;
global using GrowConditions.Api.QueryHandlers;
global using GrowConditions.Contract;
global using System.Text.Json;
global using UserManagement.Contract.ViewModels;
