# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy Plant Catalog
on:
 push:
    branches: 
      - main
    paths:
      - "src/PlantCatalog/**"
 pull_request:
     branches: 
       - main
     paths:
      - "src/PlantCatalog/**"
 workflow_dispatch:

env:
  PROJECT_NAME_FOR_DOCKER: true
  CONTAINER_APP_NAME: testapi-containergroup
  DOCKER_FILE_PATH: src/PlantCatalog/Test.Api/Dockerfile  
  
jobs:
  
  
  register_image:    
  
    runs-on: ubuntu-latest 
    steps:    
    - uses: Azure/login@v1
      with:
       creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Retrieve Container Registry Creds
      uses: azure/CLI@v1
      with:
       inlineScript: |
           echo registry-username=$(az keyvault secret show --name "registry-username" --vault-name "gardenlogvault" --query "value" -o tsv) >> $GITHUB_ENV
           echo registry-password=$(az keyvault secret show --name "registry-password" --vault-name "gardenlogvault" --query "value" -o tsv) >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3      
    - name: Log in to container registry
      uses: docker/login-action@v3
      with:
        registry: GLContRegistry.azurecr.io
        username: ${{env.registry-username}}
        password: ${{env.registry-password}}        
    - name: Build and push container image to registry
      uses: docker/build-push-action@v5.1.0
      with:
        push: true
        tags: GLContRegistry.azurecr.io/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
        file: ${{ env.DOCKER_FILE_PATH }}
      
  deploy:
   runs-on: ubuntu-latest
   needs: [ register_image]
   
   steps:   
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy Container App
      uses: azure/container-apps-deploy-action@v2
      with:
        containerAppName: ${{env.CONTAINER_APP_NAME}}
        resourceGroup: GardenLog_ResourceGroup
        imageToDeploy: GLContRegistry.azurecr.io/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}

