# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy PlantCatalog

on:
  push:
    branches:
      - main
    paths: 
      - "src/PlantCatalog/**"
  pull_request:
    branches:
      - main
    paths: 
      - "src/PlantCatalog/**"
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    env:
      mongodb-server: ${{ secrets.mongodb_password }}
      mongodb-databasename: ${{ secrets.mongodb_password }}
      mongodb-username: ${{ secrets.mongodb_password }}
      mongodb-password: ${{ secrets.mongodb_password }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test ~/work/GardenLog.V2024/GardenLog.V2024/tests/PlantCatalog.IntegrationTest/PlantCatalog.IntegrationTest.csproj -c Release --no-build --verbosity normal
