# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy Plant Catalog

on:
 push:
    branches: 
      - main
    paths:
      - "src/PlantCatalog/**"
 pull_request:
     branches: 
       - main
     paths:
      - "src/PlantCatalog/**"
 workflow_dispatch:
  
jobs:
  setup:
    runs-on: ubuntu-latest
    
    outputs:
      test-mongodb-server: ${{steps.retrieve_secrets.outputs.test-mongodb-server}}
      test-mongodb-databasename: ${{steps.retrieve_secrets.outputs.test-mongodb-databasename}}
      test-mongodb-username: ${{steps.retrieve_secrets.outputs.test-mongodb-username}}
      test-mongodb-password: ${{steps.retrieve_secrets.outputs.test-mongodb-password}}
      auth0-clientsecret: ${{steps.retrieve_secrets.outputs.auth0-clientsecret}}
      
    steps: 
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - id: retrieve_secrets
      name: Retrieve secret from KV
      uses: azure/CLI@v1
      with:
        inlineScript: |
            echo test-mongodb-server=$(az keyvault secret show --name "test-mongodb-server" --vault-name "gardenlogvault" --query "value") >> $GITHUB_OUTPUT
            echo test-mongodb-databasename=$(az keyvault secret show --name "test-mongodb-databasename" --vault-name "gardenlogvault" --query "value") >> $GITHUB_OUTPUT
            echo test-mongodb-username=$(az keyvault secret show --name "test-mongodb-username" --vault-name "gardenlogvault" --query "value") >> $GITHUB_OUTPUT
            echo test-mongodb-password=$(az keyvault secret show --name "test-mongodb-password" --vault-name "gardenlogvault" --query "value") >> $GITHUB_OUTPUT
            echo auth0-clientsecret=$(az keyvault secret show --name "auth0-clientsecret" --vault-name "gardenlogvault" --query "value") >> $GITHUB_OUTPUT
  build:
    
    env:
      mongodb-server: ${{needs.setup.outputs.test-mongodb-server}}
      mongodb-databasename: ${{needs.setup.outputs.test-mongodb-databasename}}
      mongodb-username: ${{needs.setup.outputs.test-mongodb-username}}
      mongodb-password: ${{needs.setup.outputs.test-mongodb-password}}
      auth0-clientsecret: ${{needs.setup.outputs.auth0-clientsecret}}
      
    needs: setup
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Debug
      run: |
        echo '${{needs.setup.outputs.auth0-clientsecret}}'
        echo '${{env.auth0-clientsecret}}'
    - name: Test
      run: dotnet test --logger "console;verbosity=detailed" --no-build --verbosity normal
